services:
  app:
    build: .
    container_name: schluckauf
    ports:
      - "8087:8080"
    volumes:
      - ./docker/photos:/photos
      - ./docker/data:/data
      - ./docker/trash:/trash
      - ./docker/scans:/scans
    restart: unless-stopped
