services:
  app:
    build: .
    container_name: schluckauf
    ports:
      - "8087:8080"
    volumes:
      - ./test/resources/images:/photos
      - ./data:/data
      - ./trash:/trash
      - ./scans:/scans
    restart: unless-stopped
